### ISSUE TITLE
Update readme with last input syntax

### ISSUE THREAD

**Issue by Sispheor** [bacardi55/kalliope-gmaps#1]
Hi @bacardi55 
Can you please update you example to use the [new syntax with args](https://github.com/kalliope-project/kalliope/blob/master/Docs/neurons.md#input-values)?

If you don't want to handle this neuron anymore, do you want to push it into kalliope project so we can maintain it?

Thanks a lot !

**Comment by Sispheor** [comment]
Also the tittle is "kalliope-mpd" :)

**Comment by bacardi55** [comment]
Thanks, done
